git:
  requireCleanWorkingDir: false
  requireUpstream: true
  requireCommits: true
  addUntrackedFiles: false
  commit: true
  commitMessage: "chore: release v${version}"
  tag: true
  tagName: "v${version}"
  push: true

npm:
  publish: true
  publishPath: "."
  publishConfig:
    registry: "https://registry.npmjs.org/"
  skipChecks: true

github:
  release: true
  releaseName: "Release ${version}"

hooks:
  before:init:
    - git fetch --all
    - git pull origin
    - pnpm install
    - pnpm build

plugins:
  '@release-it/conventional-changelog':
    infile: './CHANGELOG.md'
    preset:
      name: 'conventionalcommits'
      types:
        - { type: 'feat', section: 'Features' }
        - { type: 'feature', section: 'Features' }
        - { type: 'fix', section: 'Bug Fixes' }
        - { type: 'docs', section: 'Documentation' }
        - { type: 'chore', section: 'Chores' }
        - { type: 'ref', section: 'Refactor' }
    writerOpts:
      commitGroupsSort: |
        (a, b) => {
          const groupOrder = ['Features', 'Bug Fixes', 'Chores', 'Documentation', 'Refactor'];
          return groupOrder.indexOf(a.title) - groupOrder.indexOf(b.title);
        }
      commitsSort: |
        (a, b) => {
          if (a.scope || b.scope) {
            if (!a.scope) return -1;
            if (!b.scope) return 1;
            return a.scope === b.scope
              ? a.subject.localeCompare(b.subject)
              : a.scope.localeCompare(b.scope);
          }
          return a.subject.localeCompare(b.subject);
        }
