version: '3'

services:
  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: test
    ports:
      - "5432:5432"